---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - python3-psutil

  -name: Ensure wallpaper directory exists
   file:
     path: /home/braak/Pictures/Wallpaper
     state: directory

  - name: Copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      desk: /home/braak/Pictures/Wallpapers/wallpaper.jpg

  - name: Set wallpaper
    shell: |
      kwriteconfig5 --group Containments --group 1 --group Wallpaper --group org.kde.image --key wallpaper ~/Pictures/Wallpapers/wallpaper.jpg
      kwriteconfig5 --group Containments --group 1 --group Wallpaper --group org.kde.image --key plugin org.kde.image
      qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.reparseConfiguration
    become: false

